export interface IAsset {
    license: string | URL,
    src: string | URL,
    asset: string,
    bleed?: boolean,
}


const ASSETS: {[key: string]: IAsset} = {
    "bag": {
        license: "",
        src: "",
        asset: "images/"},
    "bar": {
        license: "",
        src: "",
        asset: "images/"},
    baseballBat: {
        license: "https://pixabay.com/service/license/",
        src: "https://pixabay.com/vectors/base-ball-bat-stick-wooden-25755/",
        asset: "images/baseballBat.svg",
    },
    "bed": {
        license: "https://pixabay.com/service/license/",
        src: "https://pixabay.com/illustrations/bed-pillow-zudeck-wooden-bed-rest-1545999/",
        asset: "images/bed.png",
        bleed: false,
    },
    "bee": {
        license: "https://pixabay.com/service/license/",
        src: "https://pixabay.com/photos/purple-pink-macro-bee-insect-4429887/",
        asset: "images/bee.jpg",
        bleed: true,
    },
    "box": {
        license: "",
        src: "",
        asset: "images/"},
    "bug": {
        license: "",
        src: "",
        asset: "images/"},
    "bun": {
        license: "",
        src: "",
        asset: "images/"},
    "bus": {
        license: "",
        src: "",
        asset: "images/"},
    "bye": {
        license: "",
        src: "",
        asset: "images/"},
    "can": {
        license: "",
        src: "",
        asset: "images/"},
    "cap": {
        license: "",
        src: "",
        asset: "images/"},
    "car": {
        license: "",
        src: "",
        asset: "images/"},
    "cat": {
        license: "",
        src: "",
        asset: "images/"},
    "cow": {
        license: "",
        src: "",
        asset: "images/"},
    "cub": {
        license: "",
        src: "",
        asset: "images/"},
    "cup": {
        license: "",
        src: "",
        asset: "images/"},
    "dad": {
        license: "",
        src: "",
        asset: "images/"},
    "dig": {
        license: "",
        src: "",
        asset: "images/"},
    "dot": {
        license: "",
        src: "",
        asset: "images/"},
    "egg": {
        license: "",
        src: "",
        asset: "images/"},
    "fan": {
        license: "",
        src: "",
        asset: "images/"},
    "fin": {
        license: "",
        src: "",
        asset: "images/"},
    "fox": {
        license: "",
        src: "",
        asset: "images/"},
    "ham": {
        license: "",
        src: "",
        asset: "images/"},
    "hen": {
        license: "",
        src: "",
        asset: "images/"},
    "hop": {
        license: "",
        src: "",
        asset: "images/"},
    "jam": {
        license: "",
        src: "",
        asset: "images/"},
    "jar": {
        license: "",
        src: "",
        asset: "images/"},
    "jet": {
        license: "",
        src: "",
        asset: "images/"},
    "leg": {
        license: "",
        src: "",
        asset: "images/"},
    "lip": {
        license: "",
        src: "",
        asset: "images/"},
    "mad": {
        license: "",
        src: "",
        asset: "images/"},
    "man": {
        license: "",
        src: "",
        asset: "images/"},
    "map": {
        license: "",
        src: "",
        asset: "images/"},
    "mat": {
        license: "",
        src: "",
        asset: "images/"},
    "mom": {
        license: "",
        src: "",
        asset: "images/"},
    "mop": {
        license: "",
        src: "",
        asset: "images/"},
    "mug": {
        license: "",
        src: "",
        asset: "images/"},
    "nap": {
        license: "",
        src: "",
        asset: "images/"},
    "net": {
        license: "",
        src: "",
        asset: "images/"},
    "nut": {
        license: "",
        src: "",
        asset: "images/"},
    "one": {
        license: "",
        src: "",
        asset: "images/"},
    "pan": {
        license: "",
        src: "",
        asset: "images/"},
    "peg": {
        license: "",
        src: "",
        asset: "images/"},
    "pen": {
        license: "",
        src: "",
        asset: "images/"},
    "pet": {
        license: "",
        src: "",
        asset: "images/"},
    "pig": {
        license: "",
        src: "",
        asset: "images/"},
    "pin": {
        license: "",
        src: "",
        asset: "images/"},
    "pop": {
        license: "",
        src: "",
        asset: "images/"},
    "pot": {
        license: "",
        src: "",
        asset: "images/"},
    "pup": {
        license: "",
        src: "",
        asset: "images/"},
    "rag": {
        license: "",
        src: "",
        asset: "images/"},
    "ram": {
        license: "",
        src: "",
        asset: "images/"},
    "ran": {
        license: "",
        src: "",
        asset: "images/"},
    "rat": {
        license: "",
        src: "",
        asset: "images/"},
    "red": {
        license: "",
        src: "",
        asset: "images/"},
    "rub": {
        license: "",
        src: "",
        asset: "images/"},
    "rug": {
        license: "",
        src: "",
        asset: "images/"},
    "run": {
        license: "",
        src: "",
        asset: "images/"},
    "rut": {
        license: "",
        src: "",
        asset: "images/"},
    "sad": {
        license: "",
        src: "",
        asset: "images/"},
    "sat": {
        license: "",
        src: "",
        asset: "images/"},
    "she": {
        license: "",
        src: "",
        asset: "images/"},
    "sip": {
        license: "",
        src: "",
        asset: "images/"},
    "sit": {
        license: "",
        src: "",
        asset: "images/"},
    "sob": {
        license: "",
        src: "",
        asset: "images/"},
    "sun": {
        license: "",
        src: "",
        asset: "images/"},
    "tag": {
        license: "",
        src: "",
        asset: "images/"},
    "tan": {
        license: "",
        src: "",
        asset: "images/"},
    "tap": {
        license: "",
        src: "",
        asset: "images/"},
    "ten": {
        license: "",
        src: "",
        asset: "images/"},
    "three": {
        license: "",
        src: "",
        asset: "images/"},
    "tip": {
        license: "",
        src: "",
        asset: "images/"},
    "top": {
        license: "",
        src: "",
        asset: "images/"},
    "tub": {
        license: "",
        src: "",
        asset: "images/"},
    "tug": {
        license: "",
        src: "",
        asset: "images/"},
    "two": {
        license: "",
        src: "",
        asset: "images/"},
    "van": {
        license: "",
        src: "",
        asset: "images/"},
    "wag": {
        license: "",
        src: "",
        asset: "images/"},
    "wet": {
        license: "",
        src: "",
        asset: "images/"},
    "wig": {
        license: "",
        src: "",
        asset: "images/"},
    "win": {
        license: "",
        src: "",
        asset: "images/"},
    "yam": {
        license: "",
        src: "",
        asset: "images/"},
};

const IMAGE_WORDS: {[key: string]: string[] } = {    
    bat: ['baseballBat']
}

export default ASSETS;
